### ISSUE TITLE
Support for directories within templates

### ISSUE THREAD

**Issue by domhadfield** [galElmalah/scaffolder#4]
Hey man, love the lib, very useful.

Have you considered adding support for directories within the templates?

**Comment by galElmalah** [comment]
@domhadfield 
Hey, glad to hear that you find it useful!
I have, will probably support this feature by the end of this weekend :)

**Comment by galElmalah** [comment]
Resolved in v1.4.4.
Added support for nested templates.
Let me know if you encounter any problems!
And thanks again for the feedback 😄
