### ISSUE TITLE
toUpperCase converts to lower case

### ISSUE THREAD

**Issue by fhanggi** [galElmalah/scaffolder#82]
![image](https://user-images.githubusercontent.com/1733854/159529458-ca6734f9-9830-42cf-8555-9dfe200348a5.png)

Hello
The toUpperCase transformer converts to lower case. I hope you can change that.
Thank you.
Fabian

**Comment by galElmalah** [comment]
I’ll fix this, thanks @fhanggi

**Comment by galElmalah** [comment]
fixed in `1.10.1` of the cli

**Comment by fhanggi** [comment]
Hi galElmalah, I installed 1.10.1 but it's still converting to lower case

Here is what i am trying to do 
export const {{componentName | toUpperCase}} = (props) => {

**Comment by galElmalah** [comment]
You are right, sorry.
The latest version got the correct default transformer

**Comment by fhanggi** [comment]
Great. Working now. Thank you very much.
